In [1]:
# Explore um pouco o módulo “math”. Que funções ou constantes podem ser interessantes?

In [3]:
import math

In [6]:
# valor de pi
math.pi

3.141592653589793

In [8]:
# raiz quadrada
math.sqrt(9)

3.0

In [10]:
# fatorial
math.factorial(5)

120

In [11]:
# Crie um array com a seguinte característica: [[3 4 5] [5 6 4] [5 3 2]]. Calcule a dimensão dessa matriz. Qual o
# determinante e a inversa dessa matriz? Extraia estatísticas descritivas dessa matriz (mínimo, média, máximo e
# desvio padrão).

In [12]:
import numpy as np

In [18]:
arr = np.array([(3,4,5),(5,6,4), (5,3,2)])

In [19]:
arr.shape

(3, 3)

In [23]:
det = np.linalg.det(arr)
det

-35.00000000000001

In [25]:
matriz_inversa = np.linalg.inv(arr)
matriz_inversa

array([[ 0.        , -0.2       ,  0.4       ],
       [-0.28571429,  0.54285714, -0.37142857],
       [ 0.42857143, -0.31428571,  0.05714286]])

In [28]:
print(np.min(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.std(arr))

2
4.111111111111111
6
1.1967032904743342


In [29]:
# Gere 2 matrizes com numeros inteiros aleatórios e promova a multiplicação entre elas. Houve algum erro? Qual
# a condição para que seja possível a multiplicação de 2 matrizes? Qual deve ser o formato da matriz resultante?

In [34]:
A = np.random.randint(1,100,[3,3])
print(A)
B = np.random.randint(-5,20,[3,6])
print(B)

[[85 38 46]
 [98 94 74]
 [94 80 11]]
[[ 2  6 -4  1 -2 -5]
 [-4 14  0 18 16  7]
 [ 8 -4 -1  1 -5  1]]


In [36]:
A.dot(B)

array([[ 386,  858, -386,  815,  208, -113],
       [ 412, 1608, -466, 1864,  938,  242],
       [ -44, 1640, -387, 1545, 1037,  101]])

In [37]:
# É necessário que o número de colunas da primeira matriz seja igual ao numero de linhas da segunda matriz, e a matriz
# resultante tem o número de linhas da primeira matriz e o número de colunas da segunda matriz

In [38]:
# Gere um array que seja uma sequência de números de 0 a 10, com razão de 1.2.

In [40]:
arr2 = np.arange(0,10,1.2)
print(arr2)

[0.  1.2 2.4 3.6 4.8 6.  7.2 8.4 9.6]


In [41]:
# Gere um array que seja uma sequência de números de 100 a 10, com razão de -15.

In [43]:
arr3 = np.arange(100,10,-15)
print(arr3)

[100  85  70  55  40  25]


In [44]:
# Gere uma matriz de 6x6, sendo cada linha uma sugestão aleatória de dezenas para um jogo da megasena.

In [70]:
matriz_megasena = np.random.randint(1,61,[6,6])
print(matriz_megasena)

[[47 12 36 53 15 57]
 [60  2 24  6  9 49]
 [14 18 45 60 18 26]
 [31 13 33 48 40 33]
 [12 16 26 56 20 24]
 [ 9 32 41 21 39 18]]
